version: 2

project_name: termium

builds:
  - id: termium
    dir: client
    binary: termium
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}

archives:
  - id: client
    builds:
      - termium
    name_template: "termium-client-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: codr1
    name: termium
  draft: true
  extra_files:
    - glob: dist/termium-server-*.tar.gz
