// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: proto/bc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_bc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_bc_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_bc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_bc_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ViewportSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewportSize) Reset() {
	*x = ViewportSize{}
	mi := &file_proto_bc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewportSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewportSize) ProtoMessage() {}

func (x *ViewportSize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewportSize.ProtoReflect.Descriptor instead.
func (*ViewportSize) Descriptor() ([]byte, []int) {
	return file_proto_bc_proto_rawDescGZIP(), []int{2}
}

func (x *ViewportSize) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ViewportSize) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_proto_bc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_proto_bc_proto_rawDescGZIP(), []int{3}
}

func (x *Coordinate) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Coordinate) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_proto_bc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_proto_bc_proto_rawDescGZIP(), []int{4}
}

func (x *Text) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Url struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Url) Reset() {
	*x = Url{}
	mi := &file_proto_bc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_proto_bc_proto_rawDescGZIP(), []int{5}
}

func (x *Url) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Screenshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Screenshot) Reset() {
	*x = Screenshot{}
	mi := &file_proto_bc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Screenshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screenshot) ProtoMessage() {}

func (x *Screenshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screenshot.ProtoReflect.Descriptor instead.
func (*Screenshot) Descriptor() ([]byte, []int) {
	return file_proto_bc_proto_rawDescGZIP(), []int{6}
}

func (x *Screenshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fps           int32                  `protobuf:"varint,1,opt,name=fps,proto3" json:"fps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotRequest) Reset() {
	*x = ScreenshotRequest{}
	mi := &file_proto_bc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotRequest) ProtoMessage() {}

func (x *ScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotRequest.ProtoReflect.Descriptor instead.
func (*ScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_bc_proto_rawDescGZIP(), []int{7}
}

func (x *ScreenshotRequest) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

var File_proto_bc_proto protoreflect.FileDescriptor

const file_proto_bc_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/bc.proto\x12\x02pb\"\a\n" +
	"\x05Empty\"\x1d\n" +
	"\aMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"<\n" +
	"\fViewportSize\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\"(\n" +
	"\n" +
	"Coordinate\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\" \n" +
	"\x04Text\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x17\n" +
	"\x03Url\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\" \n" +
	"\n" +
	"Screenshot\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"%\n" +
	"\x11ScreenshotRequest\x12\x10\n" +
	"\x03fps\x18\x01 \x01(\x05R\x03fps2\xa9\x02\n" +
	"\x0eBrowserControl\x12#\n" +
	"\aOpenTab\x12\t.pb.Empty\x1a\v.pb.Message\"\x00\x12.\n" +
	"\vSetViewport\x12\x10.pb.ViewportSize\x1a\v.pb.Message\"\x00\x12+\n" +
	"\n" +
	"ClickMouse\x12\x0e.pb.Coordinate\x1a\v.pb.Message\"\x00\x12,\n" +
	"\x11SendKeyboardInput\x12\b.pb.Text\x1a\v.pb.Message\"\x00\x12'\n" +
	"\rNavigateToUrl\x12\a.pb.Url\x1a\v.pb.Message\"\x00\x12>\n" +
	"\x11StreamScreenshots\x12\x15.pb.ScreenshotRequest\x1a\x0e.pb.Screenshot\"\x000\x01B\x10Z\x0etermium/src/pbb\x06proto3"

var (
	file_proto_bc_proto_rawDescOnce sync.Once
	file_proto_bc_proto_rawDescData []byte
)

func file_proto_bc_proto_rawDescGZIP() []byte {
	file_proto_bc_proto_rawDescOnce.Do(func() {
		file_proto_bc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bc_proto_rawDesc), len(file_proto_bc_proto_rawDesc)))
	})
	return file_proto_bc_proto_rawDescData
}

var file_proto_bc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_bc_proto_goTypes = []any{
	(*Empty)(nil),             // 0: pb.Empty
	(*Message)(nil),           // 1: pb.Message
	(*ViewportSize)(nil),      // 2: pb.ViewportSize
	(*Coordinate)(nil),        // 3: pb.Coordinate
	(*Text)(nil),              // 4: pb.Text
	(*Url)(nil),               // 5: pb.Url
	(*Screenshot)(nil),        // 6: pb.Screenshot
	(*ScreenshotRequest)(nil), // 7: pb.ScreenshotRequest
}
var file_proto_bc_proto_depIdxs = []int32{
	0, // 0: pb.BrowserControl.OpenTab:input_type -> pb.Empty
	2, // 1: pb.BrowserControl.SetViewport:input_type -> pb.ViewportSize
	3, // 2: pb.BrowserControl.ClickMouse:input_type -> pb.Coordinate
	4, // 3: pb.BrowserControl.SendKeyboardInput:input_type -> pb.Text
	5, // 4: pb.BrowserControl.NavigateToUrl:input_type -> pb.Url
	7, // 5: pb.BrowserControl.StreamScreenshots:input_type -> pb.ScreenshotRequest
	1, // 6: pb.BrowserControl.OpenTab:output_type -> pb.Message
	1, // 7: pb.BrowserControl.SetViewport:output_type -> pb.Message
	1, // 8: pb.BrowserControl.ClickMouse:output_type -> pb.Message
	1, // 9: pb.BrowserControl.SendKeyboardInput:output_type -> pb.Message
	1, // 10: pb.BrowserControl.NavigateToUrl:output_type -> pb.Message
	6, // 11: pb.BrowserControl.StreamScreenshots:output_type -> pb.Screenshot
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bc_proto_init() }
func file_proto_bc_proto_init() {
	if File_proto_bc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bc_proto_rawDesc), len(file_proto_bc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bc_proto_goTypes,
		DependencyIndexes: file_proto_bc_proto_depIdxs,
		MessageInfos:      file_proto_bc_proto_msgTypes,
	}.Build()
	File_proto_bc_proto = out.File
	file_proto_bc_proto_goTypes = nil
	file_proto_bc_proto_depIdxs = nil
}
